name: Unit tests with Codecov
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    name: Run unit tests with codecov upload
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.7'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade wheel
        pip3 install pyflakes
        pip3 install -r tests/test_requirements.txt
        pip3 install -e .

    - name: Static code checking with pyflakes
      run: |
        pyflakes mkdocs_glightbox

    - name: Run unit tests
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "githubaction@gmail.com"
        pytest --cov=mkdocs_glightbox --cov-report=xml
  
    - name: Upload coverage to Codecov
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false
