name: Unit tests
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    name: Run unit tests with codecov upload
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade wheel
        pip3 install pyflakes
        pip3 install -r tests/test_requirements.txt
        pip3 install -e .

    - name: Static code checking with pyflakes
      run: |
        pyflakes mkdocs_swagger_ui_tag

    - name: Run unit tests
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "githubaction@gmail.com"
        pytest --cov=mkdocs_swagger_ui_tag
